//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.ORT2.StepHelpers.ObjectRepository.ORT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ORTSmoke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ORTSmoke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flux.ORT2.StepHelpers.ObjectRepository.ORT.ORTSmoke", typeof(ORTSmoke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[2].
        /// </summary>
        internal static string alertSupport_XP {
            get {
                return ResourceManager.GetString("alertSupport_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit-button.
        /// </summary>
        internal static string bthSubmit_id {
            get {
                return ResourceManager.GetString("bthSubmit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;f3b22ca1-adcb-4977-948f-b12e1601cdba_mn_active&quot;]/div/form/button[1].
        /// </summary>
        internal static string btnFilter_XP {
            get {
                return ResourceManager.GetString("btnFilter_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[2]/div[1]/a.
        /// </summary>
        internal static string btnNewReport_XP {
            get {
                return ResourceManager.GetString("btnNewReport_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/form/div[4]/div/button.
        /// </summary>
        internal static string btnRunReport_XP {
            get {
                return ResourceManager.GetString("btnRunReport_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div/div[1]/div/div/form/div[9]/div[2]/button.
        /// </summary>
        internal static string btnSupport_XP {
            get {
                return ResourceManager.GetString("btnSupport_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAllMultiSelect.
        /// </summary>
        internal static string chkSelectProgram_id {
            get {
                return ResourceManager.GetString("chkSelectProgram_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;FiscalYear&quot;].
        /// </summary>
        internal static string ddlFiscalYear_XP {
            get {
                return ResourceManager.GetString("ddlFiscalYear_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedOmbudsDatabase.
        /// </summary>
        internal static string ddlOMBDatabase_id {
            get {
                return ResourceManager.GetString("ddlOMBDatabase_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report-source-select.
        /// </summary>
        internal static string ddlReportSource_id {
            get {
                return ResourceManager.GetString("ddlReportSource_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/h1.
        /// </summary>
        internal static string lblTableA1CreatePage_XP {
            get {
                return ResourceManager.GetString("lblTableA1CreatePage_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analysis-link.
        /// </summary>
        internal static string lnkAnalysis_id {
            get {
                return ResourceManager.GetString("lnkAnalysis_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lnkCancel_lt {
            get {
                return ResourceManager.GetString("lnkCancel_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear-filters.
        /// </summary>
        internal static string lnkClearFilters_id {
            get {
                return ResourceManager.GetString("lnkClearFilters_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;help&quot;].
        /// </summary>
        internal static string lnkCustomerSupport_XP {
            get {
                return ResourceManager.GetString("lnkCustomerSupport_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report-link.
        /// </summary>
        internal static string lnkReport_id {
            get {
                return ResourceManager.GetString("lnkReport_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;4c5e30d9-b4d0-436f-af0d-f5ec5e122309&quot;]/a[1].
        /// </summary>
        internal static string lnkReportStatusFilter_XP {
            get {
                return ResourceManager.GetString("lnkReportStatusFilter_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table A1 - Selected Information by State and Region.
        /// </summary>
        internal static string lnkTableA1_lt {
            get {
                return ResourceManager.GetString("lnkTableA1_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;4473503b-a98a-4d13-965e-7b09bf86e8e7&quot;]/li[6]/span.
        /// </summary>
        internal static string spanFilter_XP {
            get {
                return ResourceManager.GetString("spanFilter_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnnuesWorkHrFte.
        /// </summary>
        internal static string txtAnnuesWorkHrFte_id {
            get {
                return ResourceManager.GetString("txtAnnuesWorkHrFte_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string txtComments_id {
            get {
                return ResourceManager.GetString("txtComments_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddress.
        /// </summary>
        internal static string txtEmailAddress_id {
            get {
                return ResourceManager.GetString("txtEmailAddress_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string txtFirstName_id {
            get {
                return ResourceManager.GetString("txtFirstName_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiscalYear1.
        /// </summary>
        internal static string txtFiscalYear1_id {
            get {
                return ResourceManager.GetString("txtFiscalYear1_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string txtLastName_id {
            get {
                return ResourceManager.GetString("txtLastName_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string txtMessage_id {
            get {
                return ResourceManager.GetString("txtMessage_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string txtSubject_id {
            get {
                return ResourceManager.GetString("txtSubject_id", resourceCulture);
            }
        }
    }
}
