// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flux.ORT2.Features.ORT
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ORTSmokeTCs")]
    public partial class ORTSmokeTCsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ORTSmokeTCs.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ORTSmokeTCs", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Open analysis report")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public virtual void OpenAnalysisReport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Open analysis report", new string[] {
                        "Smoke"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("User is logged In \'ORT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.And("User is on ORT landing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
testRunner.And("User navigates to page \'Analysis\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
testRunner.And("User Opens analysis report \'Table A1 - Selected Information by State and Region\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
testRunner.When("User navigates to Creation page of analysis report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FiscalYear1"});
            table1.AddRow(new string[] {
                        "2016"});
#line 12
testRunner.But("User enters following \'report details\'", ((string)(null)), table1, "But ");
#line 15
testRunner.And("User runs report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
testRunner.Then("Report should be generated in excel file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User can contact to support team via contact support")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public virtual void UserCanContactToSupportTeamViaContactSupport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User can contact to support team via contact support", new string[] {
                        "Smoke"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
testRunner.Given("User is logged In \'ORT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
testRunner.And("User navigates to page \'ContactSupport\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "LastName",
                        "EmailAddress",
                        "Subject",
                        "Message"});
            table2.AddRow(new string[] {
                        "Ross",
                        "Gray",
                        "ross@mediware.com",
                        "TestSubject",
                        "TestMessage"});
#line 22
testRunner.When("User enters \'support details\' as follows", ((string)(null)), table2, "When ");
#line 25
testRunner.And("sends request to support", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
testRunner.Then("Request should be submitted successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User creates new report")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public virtual void UserCreatesNewReport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User creates new report", new string[] {
                        "Smoke"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
testRunner.Given("User is logged In \'ORT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
testRunner.And("User navigates to page \'Reports\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
testRunner.And("tries to access \'New report\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Comments"});
            table3.AddRow(new string[] {
                        "Creating report"});
#line 33
testRunner.When("User enters following \'details\' to create blank report", ((string)(null)), table3, "When ");
#line 36
testRunner.And("User saves report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
testRunner.Then("Report should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User creates new report using import")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public virtual void UserCreatesNewReportUsingImport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User creates new report using import", new string[] {
                        "Smoke"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
testRunner.Given("User is logged In \'ORT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
testRunner.And("User navigates to page \'Reports\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
testRunner.And("tries to access \'New report\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReportSource",
                        "FiscalYear",
                        "OmbudsManagerDatabase",
                        "AnnualWorkHoursperFTE",
                        "Comments"});
            table4.AddRow(new string[] {
                        "OmbudsManager Import",
                        "2016",
                        "OMBUDS_WI_STATE_7019",
                        "10",
                        "Creating report through OMB Import"});
#line 44
testRunner.When("enter following \'details\' to import report", ((string)(null)), table4, "When ");
#line 47
testRunner.And("User saves report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
testRunner.Then("Report should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

